apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: drn-list-pending
  title: List Pending DRNs
  description: Fetches DRN documents with a custom action and renders the results in the UI.
spec:
  owner: user:guest
  type: run

  # Optional form so the user can include "approved" docs too.
  parameters:
    - title: Options
      properties:
        includeApproved:
          title: Include approved DRNs as well
          type: boolean
          default: false

  steps:
    - id: fetch-drns
      name: Fetch DRNs
      action: drn:pending:list
      input:
        includeApproved: ${{ parameters.includeApproved }}

    # A small log that is visible in the task log UI
    - id: summary-log
      name: Log summary
      action: debug:log
      input:
        message: >
          Retrieved ${{ steps['fetch-drns'].output.documents | pick('length') }}
          DRN document(s) (includeApproved=${{ parameters.includeApproved }})

  # Everything here is shown on the Results page after the run completes.

  # output:
  #   text:
  #     - title: DRN Table
  #       content: |+

  #           | DRN    | Business Unit | Requester               | Architecture Review | State | Created At  |
  #           |--------|----------------|-------------------------|---------------------|----------|-------------|
  #           | DRN001 | Finance        | john.doe@example.com    | Pending             | pending    | 2024-01-15  |
  #           | DRN002 | Engineering    | jane.smith@example.com  | In Progress         | pending    | 2025-06-12  |
  #           | DRN003 | Itsvc          | chris.w@example.com  | In Progress         | rejected   | 2024-08-12  |
  #           | DRN004 | Cloud          | andy.q@example.com  | In Progress         | pending    | 2025-03-19  |
  #           | DRN005 | Engineering    | mike.m@example.com  | completed           | approved   | 2025-11-11  |

  output:
    links:
      - title: Open DRN Review UI
        url: /drns/review?includeApproved=${{ parameters.includeApproved }}
      
      - text:
        content: |
          DRNs fetched successfully.
          Opend **DRN Review UI** to select a DRN and approve/reject
          